// src/nucleo/planificacion/zonas.constantes.ts

export const TABLA_PORCENTAJES = [
    { reps: 1, porcentaje: 100.0 },
    { reps: 2, porcentaje: 94.3 },
    { reps: 3, porcentaje: 90.6 },
    { reps: 4, porcentaje: 88.1 },
    { reps: 5, porcentaje: 85.6 },
    { reps: 6, porcentaje: 83.1 },
    { reps: 7, porcentaje: 80.7 },
    { reps: 8, porcentaje: 78.6 },
    { reps: 9, porcentaje: 76.5 },
    { reps: 10, porcentaje: 74.4 },
    { reps: 11, porcentaje: 72.3 },
    { reps: 12, porcentaje: 70.3 },
    { reps: 13, porcentaje: 68.8 },
    { reps: 14, porcentaje: 67.5 },
    { reps: 15, porcentaje: 66.2 },
    { reps: 16, porcentaje: 65.0 },
    { reps: 17, porcentaje: 63.8 },
    { reps: 18, porcentaje: 62.7 },
]

export const ZONAS_INTENSIDAD = {
    NEURAL: {
        nombre: 'Neural',
        subtitulo: 'Fuerza pura — predominancia neurológica',
        repsMin: 1,
        repsMax: 5,
        porcentaje1RMMin: 85,
        porcentaje1RMMax: 100,
        tiempoDescansoMin: 3,   // minutos
        tiempoDescansoMax: 5,
        cadencia: '2-3/0/X',
        duracionSerie: '20 seg o menos',
        tipoEjercicio: 'Compuestos',
        efecto: 'Aumento de fuerza con poca hipertrofia. Mejora del impulso neurológico.',
        frecuenciaEstimulacion: '45-100 Hz',
        fibraReclutada: 'ST + FTa + FTb',
        color: '#EF4444',       // rojo
    },
    NEURO_ENDOCRINA: {
        nombre: 'Neuro-endocrina',
        subtitulo: 'Fuerza máxima + hipertrofia',
        repsMin: 6,
        repsMax: 8,
        porcentaje1RMMin: 78,
        porcentaje1RMMax: 84,
        tiempoDescansoMin: 2,
        tiempoDescansoMax: 3,
        cadencia: '3-4/0/1',
        duracionSerie: '20-30 seg',
        tipoEjercicio: 'Compuestos',
        efecto: 'Ganancias óptimas de fuerza máxima e hipertrofia simultáneas.',
        frecuenciaEstimulacion: '30-45 Hz',
        fibraReclutada: 'ST + FTa',
        color: '#FF6B00',       // naranja
    },
    HIPERTROFIA: {
        nombre: 'Hipertrofia',
        subtitulo: 'Crecimiento muscular — predominancia endocrina',
        repsMin: 9,
        repsMax: 12,
        porcentaje1RMMin: 70,
        porcentaje1RMMax: 77,
        tiempoDescansoMin: 1,
        tiempoDescansoMax: 2,
        cadencia: '3/0/2',
        duracionSerie: '30-40 seg',
        tipoEjercicio: 'Compuestos',
        efecto: 'Mejoras de las ganancias de hipertrofia más que de fuerza máxima.',
        frecuenciaEstimulacion: '30 Hz',
        fibraReclutada: 'ST + FTa',
        color: '#22C55E',       // verde
    },
    RESISTENCIA: {
        nombre: 'Resistencia',
        subtitulo: 'Hipertrofia sarcoplasmática + vascularización',
        repsMin: 13,
        repsMax: 99,            // sin límite superior
        porcentaje1RMMin: 0,
        porcentaje1RMMax: 68,
        tiempoDescansoMin: 1,
        tiempoDescansoMax: 2,
        cadencia: '3/0/2',
        duracionSerie: '40-70 seg',
        tipoEjercicio: 'Compuestos o aislamiento',
        efecto: 'Ganancias de fuerza resistencia con poca hipertrofia miofibrilar.',
        frecuenciaEstimulacion: '15 Hz',
        fibraReclutada: 'Fibras ST',
        color: '#60A5FA',       // azul
    },
}

export const TIPOS_CARGA_MESOCICLO = {
    INTRODUCTORIA: {
        nombre: 'Introductoria',
        descripcion: 'Volumen e intensidad bajos. Acostumbrar al cliente al trabajo y los ejercicios.',
        volumenRelativo: '40-60% del volumen de base',
        intensidadRelativa: 'Baja',
        ideal: 'Inicio de plan, regreso tras pausa prolongada, principiantes absolutos.',
        duracionRecomendada: '2-3 semanas',
        color: '#8A9BBF',
    },
    BASE: {
        nombre: 'Base',
        descripcion: 'Volumen de entrenamiento máximo. Gran cantidad de trabajo sostenido.',
        volumenRelativo: '100% (semana de mayor volumen del macrociclo)',
        intensidadRelativa: 'Moderada',
        ideal: 'Fase de acumulación principal. El cliente puede tolerar la carga.',
        duracionRecomendada: '3-4 semanas',
        color: '#22C55E',
    },
    CHOQUE: {
        nombre: 'Choque',
        descripcion: 'Volumen reducido al 70-80% del de base. Intensidad muy alta. Cargas máximas.',
        volumenRelativo: '70-80% del volumen de base',
        intensidadRelativa: 'Muy alta',
        ideal: 'Bloque de intensificación tras mesociclo de base.',
        duracionRecomendada: '2-3 semanas',
        color: '#FF6B00',
    },
    DESCARGA_TEST: {
        nombre: 'Descarga / Test',
        descripcion: 'Primeros 4 días: volumen bajo (50-60% del de base), intensidad un 5-10% inferior a la semana de choque. El 5to día: testeo de máximo en 3-4 ejercicios clave.',
        volumenRelativo: '50-60% del volumen de base',
        intensidadRelativa: 'Baja los primeros 4 días — máxima el día de testeo',
        ideal: 'Cierre de mesociclo. 2 días de descanso completo tras el testeo.',
        duracionRecomendada: '1 semana',
        color: '#A78BFA',
    },
}
